import type { Product, InventoryStats } from '../types/products.types';

export const inventoryStats: InventoryStats = {
  categorias: 3,
  produtos: 10,
  totalVendas: 25000,
  poucoEstoque: 2,
};

export const mockProducts: Product[] = [
  {
    id: '1',
    nome: 'Painel Solar 340W',
    descricao: 'Painel solar monocristalino 340W',
    tipo: 'Painel Solar',
    valor: 850,
    comprador: 'João Silva',
    dataCompra: '2024-01-10',
    dataEntrada: '2024-01-15',
    fornecedor: 'SolarTech',
    status: 'IN_STOCK',
  },
  {
    id: '2',
    nome: 'Inversor Solar 5kW',
    descricao: 'Inversor string 5kW monofásico',
    tipo: 'Inversor',
    valor: 3200,
    comprador: 'Maria Costa',
    dataCompra: '2024-02-05',
    dataEntrada: '2024-02-10',
    fornecedor: 'PowerInv',
    status: 'IN_STOCK',
  },
  {
    id: '3',
    nome: 'Estrutura Alumínio',
    descricao: 'Kit estrutura para telhado cerâmico',
    tipo: 'Estrutura',
    valor: 420,
    comprador: 'Carlos Mendes',
    dataCompra: '2024-01-20',
    dataEntrada: '2024-01-25',
    fornecedor: 'EstruturaPro',
    status: 'INSTALLED',
  },
  {
    id: '4',
    nome: 'Painel Solar 400W',
    descricao: 'Painel solar bifacial 400W',
    tipo: 'Painel Solar',
    valor: 1100,
    comprador: 'Ana Lima',
    dataCompra: '2024-03-01',
    dataEntrada: '2024-03-07',
    fornecedor: 'SolarTech',
    status: 'IN_STOCK',
  },
  {
    id: '5',
    nome: 'Inversor Solar 10kW',
    descricao: 'Inversor trifásico 10kW',
    tipo: 'Inversor',
    valor: 6800,
    comprador: 'Roberto Dias',
    dataCompra: '2024-03-15',
    dataEntrada: '2024-03-20',
    fornecedor: 'PowerInv',
    status: 'IN_STOCK',
  },
  {
    id: '6',
    nome: 'Estrutura Metálica Solo',
    descricao: 'Estrutura para instalação em solo',
    tipo: 'Estrutura',
    valor: 980,
    comprador: 'Fernanda Rocha',
    dataCompra: '2024-02-28',
    dataEntrada: '2024-03-05',
    fornecedor: 'EstruturaPro',
    status: 'INSTALLED',
  },
  {
    id: '7',
    nome: 'Painel Solar 550W',
    descricao: 'Painel solar de grande potência',
    tipo: 'Painel Solar',
    valor: 1450,
    comprador: 'Paulo Souza',
    dataCompra: '2024-04-10',
    dataEntrada: '2024-04-16',
    fornecedor: 'GreenPower',
    status: 'IN_STOCK',
  },
  {
    id: '8',
    nome: 'Inversor Micro 250W',
    descricao: 'Microinversor para instalações pequenas',
    tipo: 'Inversor',
    valor: 780,
    comprador: 'Lucia Ferreira',
    dataCompra: '2024-04-20',
    dataEntrada: '2024-04-25',
    fornecedor: 'PowerInv',
    status: 'IN_STOCK',
  },
  {
    id: '9',
    nome: 'Painel Solar 300W',
    descricao: 'Painel solar policristalino econômico',
    tipo: 'Painel Solar',
    valor: 620,
    comprador: 'André Oliveira',
    dataCompra: '2024-05-01',
    dataEntrada: '2024-05-08',
    fornecedor: 'SolarTech',
    status: 'IN_STOCK',
  },
  {
    id: '10',
    nome: 'Estrutura Telhado Metal',
    descricao: 'Estrutura para telhado metálico',
    tipo: 'Estrutura',
    valor: 560,
    comprador: 'Camila Torres',
    dataCompra: '2024-05-10',
    dataEntrada: '2024-05-16',
    fornecedor: 'EstruturaPro',
    status: 'IN_STOCK',
  },
];
