import type { Product, InventoryStats } from '../types/products.types';

export const inventoryStats: InventoryStats = {
  categorias: 14,
  produtos: 868,
  totalVendas: 25000,
  poucoEstoque: 12,
};

export const mockProducts: Product[] = [
  {
    id: '1',
    nome: 'Placa 1',
    valorCompra: 250,
    quantidade: 43,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 12,
    valorLimiteUnidade: 'Pacotes',
    validade: '11/12/22',
    disponibilidade: 'Em estoque',
  },
  {
    id: '2',
    nome: 'Placa 2',
    valorCompra: 250,
    quantidade: 22,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 12,
    valorLimiteUnidade: 'Pacotes',
    validade: '11/12/22',
    disponibilidade: 'Sem estoque',
  },
  {
    id: '3',
    nome: 'Placa 3',
    valorCompra: 500,
    quantidade: 36,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 9,
    valorLimiteUnidade: 'Pacotes',
    validade: '11/12/22',
    disponibilidade: 'Em estoque',
  },
  {
    id: '4',
    nome: 'Placa 4',
    valorCompra: 250,
    quantidade: 14,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 6,
    valorLimiteUnidade: 'Pacotes',
    validade: '11/12/22',
    disponibilidade: 'Sem estoque',
  },
  {
    id: '5',
    nome: 'Placa 5',
    valorCompra: 1500,
    quantidade: 5,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 5,
    valorLimiteUnidade: 'Pacotes',
    validade: '11/12/22',
    disponibilidade: 'Em estoque',
  },
  {
    id: '6',
    nome: 'Placa 6',
    valorCompra: 1500,
    quantidade: 10,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 5,
    valorLimiteUnidade: 'Pacotes',
    validade: '11/12/22',
    disponibilidade: 'Em estoque',
  },
  {
    id: '7',
    nome: 'Placa 7',
    valorCompra: 750,
    quantidade: 8,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 3,
    valorLimiteUnidade: 'Pacotes',
    validade: '15/03/23',
    disponibilidade: 'Pouco estoque',
  },
  {
    id: '8',
    nome: 'Placa 8',
    valorCompra: 320,
    quantidade: 60,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 20,
    valorLimiteUnidade: 'Pacotes',
    validade: '20/06/23',
    disponibilidade: 'Em estoque',
  },
  {
    id: '9',
    nome: 'Placa 9',
    valorCompra: 90,
    quantidade: 3,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 5,
    valorLimiteUnidade: 'Pacotes',
    validade: '01/01/23',
    disponibilidade: 'Sem estoque',
  },
  {
    id: '10',
    nome: 'Placa 10',
    valorCompra: 2000,
    quantidade: 25,
    quantidadeUnidade: 'Pacotes',
    valorLimite: 10,
    valorLimiteUnidade: 'Pacotes',
    validade: '30/09/23',
    disponibilidade: 'Em estoque',
  },
];
