import type { Movement, MovementStats } from '../types/movements.types';

export const movementStats: MovementStats = {
  totalPedidos: 10,
  totalRecebido: {
    quantidade: 8,
    valor: 25000,
  },
  totalRetorno: {
    quantidade: 2,
    valor: 2500,
  },
  aCaminho: 3,
};

export const mockMovements: Movement[] = [
  {
    id: '1',
    productId: '1',
    produto: 'Painel Solar 340W',
    valor: 850,
    dataEntrada: '2024-01-15',
    comprador: 'João Silva',
    descricao: 'Painel solar monocristalino 340W',
    fornecedor: 'SolarTech',
    tipo: 'Painel Solar',
    status: 'IN_STOCK',
  },
  {
    id: '2',
    productId: '2',
    produto: 'Inversor Solar 5kW',
    valor: 3200,
    dataEntrada: '2024-02-10',
    comprador: 'Maria Costa',
    descricao: 'Inversor string 5kW monofásico',
    fornecedor: 'PowerInv',
    tipo: 'Inversor',
    status: 'IN_STOCK',
  },
  {
    id: '3',
    productId: '3',
    produto: 'Estrutura Alumínio',
    valor: 420,
    dataEntrada: '2024-01-25',
    comprador: 'Carlos Mendes',
    descricao: 'Kit estrutura para telhado cerâmico',
    fornecedor: 'EstruturaPro',
    tipo: 'Estrutura',
    status: 'INSTALLED',
  },
  {
    id: '4',
    productId: '4',
    produto: 'Painel Solar 400W',
    valor: 1100,
    dataEntrada: '2024-03-07',
    comprador: 'Ana Lima',
    descricao: 'Painel solar bifacial 400W',
    fornecedor: 'SolarTech',
    tipo: 'Painel Solar',
    status: 'IN_STOCK',
  },
  {
    id: '5',
    productId: '5',
    produto: 'Inversor Solar 10kW',
    valor: 6800,
    dataEntrada: '2024-03-20',
    comprador: 'Roberto Dias',
    descricao: 'Inversor trifásico 10kW',
    fornecedor: 'PowerInv',
    tipo: 'Inversor',
    status: 'IN_STOCK',
  },
  {
    id: '6',
    productId: '6',
    produto: 'Estrutura Metálica Solo',
    valor: 980,
    dataEntrada: '2024-03-05',
    comprador: 'Fernanda Rocha',
    descricao: 'Estrutura para instalação em solo',
    fornecedor: 'EstruturaPro',
    tipo: 'Estrutura',
    status: 'INSTALLED',
  },
  {
    id: '7',
    productId: '7',
    produto: 'Painel Solar 550W',
    valor: 1450,
    dataEntrada: '2024-04-16',
    comprador: 'Paulo Souza',
    descricao: 'Painel solar de grande potência',
    fornecedor: 'GreenPower',
    tipo: 'Painel Solar',
    status: 'IN_STOCK',
  },
  {
    id: '8',
    productId: '8',
    produto: 'Inversor Micro 250W',
    valor: 780,
    dataEntrada: '2024-04-25',
    comprador: 'Lucia Ferreira',
    descricao: 'Microinversor para instalações pequenas',
    fornecedor: 'PowerInv',
    tipo: 'Inversor',
    status: 'IN_STOCK',
  },
];
