/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticar usuário e obter token JWT
         * @description Realiza o login com e-mail e senha. Em caso de sucesso, retorna o token JWT a ser utilizado nas demais requisições no header `Authorization: Bearer <token>`.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retorna dados do usuário autenticado
         * @description Retorna as informações do perfil do usuário atualmente autenticado via token JWT.
         */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todos os usuários
         * @description Retorna a lista completa de usuários cadastrados (sem o campo senha).
         */
        get: operations["UsersController_findAll"];
        put?: never;
        /**
         * Criar novo usuário
         * @description Cria um novo usuário no sistema. Este endpoint não requer autenticação.
         */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar usuário por ID
         * @description Retorna os dados de um usuário específico pelo seu ID (UUID).
         */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /**
         * Remover usuário
         * @description Remove permanentemente um usuário do sistema.
         */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /**
         * Atualizar usuário
         * @description Atualiza parcialmente os dados de um usuário. Apenas os campos informados serão alterados.
         */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar produtos com filtros e paginação
         * @description Retorna uma lista paginada de produtos. Suporta busca por texto e filtros por tipo, fornecedor, código e estoque baixo.
         */
        get: operations["ProductsController_findAll"];
        put?: never;
        /**
         * Cadastrar novo produto
         * @description Cria um novo produto no estoque. O código (UUID) é gerado automaticamente. A data de entrada em estoque (entryStockDate) também é definida automaticamente. Uma movimentação de inventário inicial (EM_ESTOQUE) é criada automaticamente.
         */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar fornecedores disponíveis
         * @description Retorna uma lista de todos os fornecedores únicos cadastrados nos produtos.
         */
        get: operations["ProductsController_getVendors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar produto por ID
         * @description Busca um produto específico pelo seu ID interno (UUID).
         */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        /**
         * Remover produto
         * @description Remove permanentemente um produto do sistema. Não é possível remover produtos que possuam movimentações de estoque registradas.
         */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /**
         * Atualizar produto
         * @description Atualiza parcialmente os dados de um produto. Apenas os campos informados serão alterados.
         */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/api/v1/products/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificar estoque disponível em tempo real
         * @description Retorna a quantidade atual em estoque do produto (calculada dinamicamente com base nas unidades disponíveis) e indica se está com estoque baixo (≤ 5 unidades).
         */
        get: operations["ProductsController_getStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar unidades de estoque com filtros e paginação
         * @description Retorna uma lista paginada de unidades individuais, com filtros opcionais por produto e status.
         */
        get: operations["InventoryController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar detalhes de uma unidade específica
         * @description Retorna os detalhes de uma unidade individual de estoque pelo seu ID.
         */
        get: operations["InventoryController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar status de uma unidade
         * @description Atualiza o status (EM_ESTOQUE, INSTALADO) e/ou as observações de uma unidade de estoque.
         */
        patch: operations["InventoryController_updateStatus"];
        trace?: never;
    };
    "/api/v1/inventory/products/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar unidades de um produto
         * @description Retorna todas as unidades de um produto específico, agrupadas e com sumário de quantidades.
         */
        get: operations["InventoryController_findByProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relatório de movimentações por período
         * @description Retorna um relatório paginado de movimentações de estoque com filtros por período, produto, tipo e fornecedor.
         */
        get: operations["ReportsController_getMovementsReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relatório de estoque atual
         * @description Retorna um resumo do estado atual do estoque, incluindo total de produtos, quantidade total de itens, e agrupamento por tipo e status de estoque (normal/baixo/zerado).
         */
        get: operations["ReportsController_getStockReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visão geral do estoque
         * @description Retorna a quantidade total de produtos em estoque (EM_ESTOQUE) e instalados (INSTALADO).
         */
        get: operations["ReportsController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/stock-by-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tipos de produtos em estoque
         * @description Distribuição de produtos EM_ESTOQUE por tipo (SOLAR_PANEL, INVERTER, STRUCTURE).
         */
        get: operations["ReportsController_getStockByType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Linha do tempo de estoque e instalações
         * @description Dados agregados por semana, mês ou ano para uso em gráficos.
         */
        get: operations["ReportsController_getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/best-selling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Produto mais vendido
         * @description Produto com maior número de movimentações INSTALADO.
         */
        get: operations["ReportsController_getBestSelling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * Format: email
             * @description Endereço de e-mail do usuário
             */
            email: string;
            /** @description Senha do usuário */
            password: string;
        };
        CreateUserDto: {
            /** @description Nome completo do usuário */
            name: string;
            /**
             * Format: email
             * @description Endereço de e-mail do usuário
             */
            email: string;
            /** @description Senha (mínimo 8 caracteres, deve conter ao menos uma maiúscula e um número) */
            password: string;
        };
        UpdateUserDto: {
            /** @description Nome completo do usuário */
            name?: string;
            /**
             * Format: email
             * @description Endereço de e-mail do usuário
             */
            email?: string;
            /** @description Nova senha (mínimo 8 caracteres, deve conter ao menos uma maiúscula e um número) */
            password?: string;
        };
        CreateProductDto: {
            /** @description Nome do produto */
            name: string;
            /** @description Nome do fornecedor */
            vendor: string;
            /** @description Nome do cliente (opcional) */
            customer?: string;
            /**
             * Format: date-time
             * @description Data de compra do produto (ISO 8601, ex: 2024-01-15T00:00:00.000Z)
             */
            purchaseDate: string;
            /** @description Custo de aquisição do produto em reais (BRL) */
            cost: number;
            /**
             * @description Tipo do produto: SOLAR_PANEL (Painel Solar), INVERTER (Inversor) ou STRUCTURE (Estrutura)
             * @enum {string}
             */
            type: "SOLAR_PANEL" | "INVERTER" | "STRUCTURE";
            /** @description Descrição detalhada do produto (opcional) */
            description?: string;
            /**
             * Format: uri
             * @description URL da imagem do produto (opcional)
             */
            image?: string;
        };
        UpdateProductDto: {
            /** @description Nome do produto */
            name?: string;
            /** @description Nome do fornecedor */
            vendor?: string;
            /** @description Nome do cliente (opcional) */
            customer?: string;
            /**
             * Format: date-time
             * @description Data de compra do produto (ISO 8601, ex: 2024-01-15T00:00:00.000Z)
             */
            purchaseDate?: string;
            /** @description Custo de aquisição do produto em reais (BRL) */
            cost?: number;
            /**
             * @description Tipo do produto: SOLAR_PANEL, INVERTER ou STRUCTURE
             * @enum {string}
             */
            type?: "SOLAR_PANEL" | "INVERTER" | "STRUCTURE";
            /** @description Descrição detalhada do produto */
            description?: string;
            /**
             * Format: uri
             * @description URL da imagem do produto
             */
            image?: string;
        };
        UpdateItemStatusDto: {
            /** @enum {string} */
            status: "EM_ESTOQUE" | "INSTALADO";
            observations?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Credenciais de acesso */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login realizado com sucesso. Retorna o token JWT e dados básicos do usuário. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais inválidas — e-mail ou senha incorretos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do usuário autenticado retornados com sucesso (sem campo senha). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de usuários retornada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dados do novo usuário */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Usuário criado com sucesso. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos — verifique nome, e-mail e senha. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail já cadastrado no sistema. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do usuário (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário encontrado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do usuário (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário removido com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do usuário (UUID) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Campos a serem atualizados (todos opcionais) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Usuário atualizado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                /** @description Busca textual por nome, código ou fornecedor */
                search?: string;
                /** @description Filtrar por nome do fornecedor */
                vendor?: string;
                /** @description Filtrar por tipo de produto */
                type?: "SOLAR_PANEL" | "INVERTER" | "STRUCTURE";
                /** @description Número da página (padrão: 1) */
                page?: unknown;
                /** @description Itens por página (padrão: 20, máx: 100) */
                limit?: unknown;
                /** @description Filtrar pelo código UUID do produto */
                code?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de produtos retornada com sucesso. Inclui metadados de paginação (total, página atual, total de páginas). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dados do produto a ser cadastrado */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Produto criado com sucesso. Retorna o objeto completo do produto criado, incluindo o código UUID gerado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos — verifique os campos obrigatórios e seus formatos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_getVendors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de nomes de fornecedores retornada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do produto (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto encontrado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado para o ID informado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do produto (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto removido com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não é possível remover produto com movimentações registradas. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do produto (UUID) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Campos a serem atualizados (todos opcionais) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Produto atualizado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_getStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único do produto (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna id, code, name, updatedAt, quantity (calculado via movimentações com status EM_ESTOQUE) e isLowStock do produto. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_findAll: {
        parameters: {
            query?: {
                /** @description Filtrar pelo ID do produto (UUID) */
                productId?: string;
                /** @description Filtrar por status da unidade */
                status?: "EM_ESTOQUE" | "INSTALADO";
                /** @description Itens por página (padrão: 20) */
                limit?: number;
                /** @description Número da página (padrão: 1) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de unidades retornada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único da unidade (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unidade encontrada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unidade não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID único da unidade (UUID) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Dados de atualização */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemStatusDto"];
            };
        };
        responses: {
            /** @description Status atualizado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unidade não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_findByProduct: {
        parameters: {
            query?: {
                /** @description Itens por página (padrão: 20) */
                limit?: number;
                /** @description Número da página (padrão: 1) */
                page?: number;
            };
            header?: never;
            path: {
                /** @description ID único do produto (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unidades retornadas com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getMovementsReport: {
        parameters: {
            query?: {
                /** @description Data de início do período (ISO 8601, ex: 2024-01-01T00:00:00Z) */
                startDate?: string;
                /** @description Data de fim do período (ISO 8601, ex: 2024-12-31T23:59:59Z) */
                endDate?: string;
                /** @description Filtrar pelo ID do produto (UUID) */
                productId?: string;
                /** @description Filtrar por status da unidade */
                status?: "EM_ESTOQUE" | "INSTALADO";
                /** @description Filtrar pelo nome do fornecedor */
                vendor?: string;
                /** @description Número da página (padrão: 1) */
                page?: unknown;
                /** @description Itens por página (padrão: 50, máx: 100) */
                limit?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relatório de movimentações retornado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getStockReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relatório de estoque retornado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado — token JWT ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visão geral retornada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getStockByType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tipos de produtos retornados com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getTimeline: {
        parameters: {
            query: {
                /** @description Data final (ISO 8601) */
                endDate?: unknown;
                /** @description Data inicial (ISO 8601) */
                startDate?: unknown;
                period: "weekly" | "monthly" | "yearly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados de timeline retornados com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getBestSelling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto mais vendido retornado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
